/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as deleteTodo from "../deleteTodo";
import type * as getTodos from "../getTodos";
import type * as insertTodo from "../insertTodo";
import type * as patchTodo from "../patchTodo";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  deleteTodo: typeof deleteTodo;
  getTodos: typeof getTodos;
  insertTodo: typeof insertTodo;
  patchTodo: typeof patchTodo;
}>;
